#!/bin/sh

clear
detox && echo "Watching for python file changes..."

watchmedo shell-command --patterns="*.py" --recursive --drop \
  --command="clear; echo \"Testing...\"; detox && sleep 1 && echo \"Watching for python file changes...\""
